#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DTC.NIN.Ukjenks.CriminalIntent.Resource", IsApplication=true)]

namespace DTC.NIN.Ukjenks.CriminalIntent
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_activated = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000d
			public const int crime_camera_progressContainer = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int crime_camera_surfaceView = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int crime_camera_takePictureButton = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int crime_date = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int crime_imageButton = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int crime_imageView = 2130968580;
			
			// aapt resource value: 0x7f040012
			public const int crime_list_item_dateTextView = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int crime_list_item_solvedCheckBox = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int crime_list_item_titleTextView = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int crime_reportButton = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int crime_solved = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int crime_suspectButton = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int crime_title = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int detailFragmentContainer = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_date_datePicker = 2130968579;
			
			// aapt resource value: 0x7f04000e
			public const int emptyTextView = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int fragmentContainer = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int initial_crimeButton = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int menu_item_delete_crime = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int menu_item_new_crime = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int menu_item_show_subtitle = 2130968597;
			
			// aapt resource value: 0x7f040000
			public const int viewPager = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragment = 2130903040;
			
			// aapt resource value: 0x7f030007
			public const int activity_masterdetail = 2130903047;
			
			// aapt resource value: 0x7f030001
			public const int activity_twopane = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_date = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_crime = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_crime_camera = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_empty_list = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_item_crime = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int crime_list_item_context = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fragment_crime_list = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int button_text = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int crime_details_label = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int crime_report = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int crime_report_no_suspect = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int crime_report_solved = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int crime_report_subject = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int crime_report_suspect = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int crime_report_text = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int crime_report_unsolved = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int crime_solved_label = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int crime_suspect_text = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int crime_title_hint = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int crime_title_label = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int crimes_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int date_picker_title = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int delete_crime = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int hide_subtitle = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int new_crime = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int send_report = 2131034135;
			
			// aapt resource value: 0x7f050008
			public const int show_subtitle = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int subtitle = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int take = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int text_view = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
